### ISSUE TITLE
object has no attribute???

### ISSUE THREAD

**Issue by BowlOfCactusJuice** [GingerAvalanche/botw_actor_tool#13]
Me not programmer, me dumb gamer, me try change the cost of some clothing a mod sells at a vendor in game.

Me use Shiny BOTW Actor Tool, ask it to find clothing piece, me find. But when me try open it, tool give me code:

```
Traceback (most recent call last):
  File "c:\users\UungaBuunga\appdata\local\programs\python\python38\lib\site-packages\botw_actor_tool\Ui_Main.py", line 224, in OnOpen
    self.LoadActor(actorpath)
  File "c:\users\UungaBuunga\appdata\local\programs\python\python38\lib\site-packages\botw_actor_tool\Ui_Main.py", line 178, in LoadActor
    self._actor = BATActor(actorpath)
  File "c:\users\UungaBuunga\appdata\local\programs\python\python38\lib\site-packages\botw_actor_tool\actor.py", line 130, in __init__
    if not self._info or (self._has_far and not self._far_info):
AttributeError: 'BATActor' object has no attribute '_info'
```

Please help dumb gamer, no me know what code mean.

**Comment by GingerAvalanche** [comment]
BAT couldn’t find an entry for your armor in the file called ActorInfo.product.sbyml

This typically means either that the mod didn’t include a copy of that file, or that you’re editing the files installed from a bnp, which stores that info elsewhere.

If you’re editing a bnp, you can use bcml’s dev tools tab to “convert bnp to standalone,” edit the standalone mod, and then install that.

**Comment by BowlOfCactusJuice** [comment]
oh geez... I don't even know what any of that is... Thank you for commenting but i feel like I'm out of my depth here. I use BCML to install my mods, but I have zero idea... "where" it actually keeps its mods.... or what to do about that.
