### ISSUE TITLE
Installation error in Python 3.10+ due to Mapping being moved from collections to collections.abc

### ISSUE THREAD

**Issue by SirMrMister** [GingerAvalanche/botw_actor_tool#17]
Error during installation in Windows:

`>pip install botw_actor_tool
Collecting botw_actor_tool
  Using cached botw_actor_tool-0.2.11-py3-none-any.whl (196 kB)
Collecting wxPython>=4.1.0 (from botw_actor_tool)
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\miste\AppData\Local\Temp\pip-install-mjp6cbmu\wxpython_6833edb19d544f049bb8568342613028\setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "C:\Users\miste\AppData\Local\Temp\pip-install-mjp6cbmu\wxpython_6833edb19d544f049bb8568342613028\buildtools\config.py", line 30, in <module>
          from attrdict import AttrDict
        File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\attrdict\__init__.py", line 5, in <module>
          from attrdict.mapping import AttrMap
        File "C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\site-packages\attrdict\mapping.py", line 4, in <module>
          from collections import Mapping
      ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\miste\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

As explained [here](https://stackoverflow.com/a/71438295), I think that Mapping needs to be imported from collections.abc instead of just connections. Either do that, or if for whatever reason it's not possible or it's being caused by a dependency, at least update the project's readme to mention it requires Python 3.7-9 instead of 3.7+.

**Comment by GingerAvalanche** [comment]
I hate python dependencies

Readme has been updated with more constrained version numbers
